[package]
name = "sdcoeff"
version = "0.2.0"
authors = ["nebelgrau <nebelgrau@gmx.com>"]
edition = "2018"

[lib]
name = "sdcoeff"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "0.11", features = ["extension-module"]}